---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      install-weak-deps: false
      packages:
        - sway
        - sway-systemd
        - mesa-vulkan-drivers
        - mesa-va-drivers
        - alacritty
        - fuzzel
        - mako
        - grim
        - slurp
        - wl-clipboard
        - swaylock
        - swayidle
        - swaybg
        - xdg-desktop-portal
        - xdg-desktop-portal-wlr
        - xdg-desktop-portal-gtk
        - xorg-x11-server-Xwayland

  - type: default-flatpaks
    configurations:
      - scope: system
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
